services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - finance_data:/var/lib/postgresql/data

volumes:
  finance_data: